<?php


namespace Tests\Feature\App\Http\Controllers;


use App\Models\Course;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ModuleControllerTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_admin_can_create_module()
    {
        // Prepare
        $user = User::factory()->create(['admin' => '1']);
        $course = Course::factory()->create();
        $this->actingAs($user);

        $payload = [
            'course_id' => $course->id,
            'name' => 'Module_Test'
        ];

        // Act
        $response = $this->post(route('post-module'), $payload);

        // Assert
        $response->assertOk();
        $this->assertDatabaseHas('modules', [
            'course_id' => $course->id,
            'name' => $payload["name"]
        ]);

    }

}
