<?php

namespace Tests\Feature\App\Http\Controllers;

use App\Models\Notification\Notification;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class NotificationControllerTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_client_can_see_notifications()
    {
        // Prepare
        $user = User::factory()->create();
        $this->actingAs($user);

        // Act
        $response = $this->get(route('get-notifications'));

        // Assert
        $response->assertViewHas('notifications');
    }

}
