<?php

namespace Tests\Feature\App\Http\Controllers;

use App\Models\User;
use Tests\TestCase;

class WalletControllerTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_user_can_update_wallet()
    {
        $user = User::factory()->create(['admin' => '1']);

        $payload = [
            'credits' => '900'
        ];

        $response = $this->actingAs($user)
            ->put(route('put-wallet', $user->id), $payload);

        $response->assertStatus(200);
    }

    public function test_user_can_not_update_wallet()
    {
        $user = User::factory()->create(['admin' => '1']);

        $payload = [];

        $response = $this->actingAs($user)
            ->put(route('put-wallet', $user->id), $payload);

        $response->assertStatus(302);
    }

}
